name: Test Multiple Versions

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: yarn install --frozen-lockfile --check-files
      - run: yarn build
      - name: Test Default
        run: yarn test:ci

  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        react:
          - 16.8.0
          - 16.9.0
          - 17.0.0
          - 18.0.0
          - 18.1.0
          - 18.2.0
          - 18.3.0-next-e225fa43a-20220711
          - 0.0.0-experimental-e225fa43a-20220711
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: yarn
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: yarn install --frozen-lockfile --check-files
      - run: yarn build
      - name: Install legacy testing-library
        if: ${{ startsWith(matrix.react, '16.') || startsWith(matrix.react, '17.') }}
        run: yarn add -D @testing-library/react@12.1.4
      - name: Patch for React 16
        if: ${{ startsWith(matrix.react, '16.') }}
        run: |
          sed -i~ '1s/^/import React from "react";/' tests/*.tsx
          sed -i~ 's/"jsx": "react-jsx"/"jsx": "react"/' package.json
          sed -i~ 's/automatic/classic/' .swcrc
      - name: Test ${{ matrix.react }}
        run: |
          yarn add -D react@${{ matrix.react }} react-dom@${{ matrix.react }}
          yarn test:ci
